# This is run inside Docker.
user nobody nobody;

# Pid storage location.
pid /var/run/nginx.pid;

# Set number of worker processes.
worker_processes auto;

# Enables the use of JIT for regular expressions to speed-up their processing.
pcre_jit on;

# Write error log to stdout instead of file
error_log /proc/1/fd/2 error;

# Load dynamic modules.
include /etc/nginx/modules/*.conf;

# Max num of simultaneous connections for each worker process.
events {
    worker_connections 512;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Define custom log format to include response times
    log_format main_timed '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for" '
                          '$request_time $upstream_response_time $pipe $upstream_cache_status';

    # Log access to stdout
    access_log /proc/1/fd/1 main_timed;

    # How long to allow each connection to stay idle.
    keepalive_timeout 65;

    # Write temporary files to /tmp so they can be created as a non-privileged user
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path /tmp/proxy_temp;
    fastcgi_temp_path /tmp/fastcgi_temp;
    uwsgi_temp_path /tmp/uwsgi_temp;
    scgi_temp_path /tmp/scgi_temp;

    # Don't buffer data to disk, keep it in memory
    proxy_buffering off;
    proxy_request_buffering off;
    fastcgi_buffering off;
    fastcgi_request_buffering off;

    # Disable sendfile as per https://docs.nginx.com/nginx/admin-guide/web-server/serving-static-content/
    sendfile off;

    # Include all other configuration files
    include /etc/nginx/http.d/*.conf;
}
